baseURL = "https://gideonler.github.io/stuff/"
languageCode = "en-us"
title = "Gideon Ler"
theme = "dario"

# Optional: enable syntax highlighting for code blocks
pygmentsUseClasses = true
# netlify.toml
[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.116.3"
[params]
  description = "A personal blog about me, my work, and hobbies."
  
  [params.author]
    name = "Gideon Ler"
    email = "gideonler@gmail.com"
    linkedin = "https://www.linkedin.com/in/gideonler/"
    github = "https://github.com/gideonler"